### ISSUE TITLE
Block View Text Overflow

### ISSUE THREAD

**Issue by 0x090909** [otterscan/otterscan#291] opened 2022-06-26 09:40 UTC
I found this bug in the block view from mobile phone.

![image](https://user-images.githubusercontent.com/16927059/175808417-ca765a27-416f-41d7-967e-3e3dfb135236.png)

**Comment by experimentalperson** [comment] 2022-06-26 09:44
![image](https://user-images.githubusercontent.com/16927059/175808537-3bcd35f2-c251-490f-abd4-a0f450b0967b.png)

**Comment by experimentalperson** [comment] 2022-06-27 11:43
> ![image](https://user-images.githubusercontent.com/16927059/175808537-3bcd35f2-c251-490f-abd4-a0f450b0967b.png)

I very much suspect this has to do with the fact that the table is built using grids and divs and not table.

**Comment by wmitsuda** [comment] 2022-06-29 18:19
It is hard to fit such an information-rich table like transaction results in narrow screens, I've been thinking in how to present them, I also don't want to cut columns.

I think there is no way other than introducing horizontal scrolling.

**Comment by experimentalperson** [comment] 2022-06-29 20:42
Do you think this is possible preserving the grids?

**Comment by sealer3** [comment] 2024-01-20 21:34
I can't reproduce this issue; the text doesn't overflow anymore, so it must have been fixed. @wmitsuda feel free to close this if you agree.

**Comment by wmitsuda** [comment] 2024-01-27 22:10
agree, I think it was fixed by another similar issue, but couldn't find it.

anyway, I tested in my phone and it doesn't overflow anymore.

**Comment by wmitsuda** [comment] 2024-01-27 22:11
actually, the tx list issue is not addressed, so reopening :)

**Comment by wmitsuda** [comment] 2024-01-27 22:16
I think we can address the tx list issue by letting it freely scroll horizontally, and in the process we can also properly set the column sizes.

maybe we need to rework how the grid is built, that's why I think I didn't work on that before. but by solving that we won't need to worry about the amount of columns/sizes anymore in any screen size.

now I think it is ok to follow this approach, that's how other explorers do it as well.

**Comment by wmitsuda** [comment] 2024-01-27 22:17
assigning @sealer3

**Closed** 2024-02-19 18:47 UTC
Labels: bug
