### ISSUE TITLE
Token value in USD (BSC)

### ISSUE THREAD

**Issue by 0x090909** [otterscan/otterscan#283] opened 2022-06-17 22:02 UTC
How can it be enabled? I've explored the source code and it seems already implemented, but the price feed does not seem to work.

is there a config file that needs to be changed?

Thanks

**Comment by wmitsuda** [comment] 2022-06-17 22:32
it should be working as long as there is a known <token>-USD price feed on chainlink, do you have some example tx to reproduce?

**Comment by experimentalperson** [comment] 2022-06-18 07:41
BNB USDT for example, in the transaction window, its written NAN

**Comment by experimentalperson** [comment] 2022-06-18 07:53
![image](https://user-images.githubusercontent.com/16927059/174428519-f1d46ea0-70f7-486e-b04e-86895dca2fd3.png)

**Comment by wmitsuda** [comment] 2022-06-20 02:52
oh right, you're syncing BSC, unfortunately I rely on Chainlink's feed registry to locate the token/USD oracle, but it does not support BSC, see: https://docs.chain.link/docs/feed-registry/#contract-addresses

I think it could be possible to have a hardcoded mapping, but it would get stale very quickly as they add more tokens to BSC, so ideally Chainlink should support a feed registry for BSC.

**Comment by wmitsuda** [comment] 2022-06-20 02:58
I opened a feature request on chainlink: https://github.com/smartcontractkit/chainlink/issues/6807

**Comment by experimentalperson** [comment] 2022-06-23 10:40
Great!

**Comment by wmitsuda** [comment] 2022-06-23 20:58
Let's wait if they reply something, otherwise we can try some ugly workaround, but I hope I can avoid it.

**Comment by experimentalperson** [comment] 2022-06-24 07:11
Cant we manually create this contract on mainnet and deploy it with the same standards it has on eth mainnet?

**Comment by sealer3** [comment] 2024-04-03 07:24
With #1899 you can specify the BNB-USD Chainlink oracle and use Uniswap price resolvers for other tokens as long as there is a popular Uniswap V2 or V3 compatible market. I think with that PR merged, we can close this unless there are any outstanding issues we haven't addressed.

**Comment by wmitsuda** [comment] 2024-04-09 17:31
I agree. I don't want us to put anything BNB specific in our code because it is not officially supported by Erigon, but as it is now, any interested party can modify Otterscan to add BNB extensions as well.

**Closed** 2024-04-09 17:31 UTC
Labels: enhancement
